#pragma once

#include <string>
#include <vector>
#include <map>
#include <nlohmann/json.hpp>

namespace midnight::zk
{

    using json = nlohmann::json;

    /**
     * @brief Raw ZK proof bytes
     * Represents a zero-knowledge proof generated by the proof server
     */
    struct ProofData
    {
        std::vector<uint8_t> proof_bytes;
        size_t size() const { return proof_bytes.size(); }

        std::string to_hex() const;
        static ProofData from_hex(const std::string &hex);

        json to_json() const;
        static ProofData from_json(const json &j);
    };

    /**
     * @brief Public inputs for circuit execution
     * These are disclosed values that appear on-chain
     */
    struct PublicInputs
    {
        std::map<std::string, std::string> inputs; // field_name => hex_value

        void add_input(const std::string &name, const std::string &hex_value);
        std::string get_input(const std::string &name) const;
        bool has_input(const std::string &name) const;

        json to_json() const;
        static PublicInputs from_json(const json &j);
    };

    /**
     * @brief Witness outputs (private data)
     * Witness functions return data that never appears on-chain
     */
    struct WitnessOutput
    {
        std::string witness_name;          // e.g., "localSecretKey"
        std::vector<uint8_t> output_bytes; // Raw output data
        std::string output_type;           // Type hint (e.g., "Bytes<32>")

        std::string to_hex() const;
        static WitnessOutput from_hex(const std::string &hex);

        json to_json() const;
        static WitnessOutput from_json(const json &j);
    };

    /**
     * @brief Circuit-specific proof metadata
     * Information about which circuit generated this proof
     */
    struct CircuitProofMetadata
    {
        std::string circuit_name;        // e.g., "post", "takeDown"
        std::string circuit_hash;        // Hash of circuit definition
        uint32_t num_constraints;        // Circuit constraint count
        std::string compilation_version; // Compact compiler version

        json to_json() const;
        static CircuitProofMetadata from_json(const json &j);
    };

    /**
     * @brief Complete ZK proof package for submission to blockchain
     * Contains proof, public inputs, and metadata
     */
    struct CircuitProof
    {
        ProofData proof;
        PublicInputs public_inputs;
        CircuitProofMetadata metadata;

        // Timestamp when proof was generated
        uint64_t generated_at_timestamp;

        // Proof server that generated it (for verification)
        std::string proof_server_endpoint;

        // Circuit parameters that were proven
        std::map<std::string, std::string> circuit_parameters;

        // Proof verification status
        enum class VerificationStatus
        {
            UNVERIFIED,
            LOCALLY_VERIFIED,
            SERVER_VERIFIED,
            BLOCKCHAIN_VERIFIED
        };
        VerificationStatus verification_status = VerificationStatus::UNVERIFIED;

        size_t total_size() const;
        json to_json() const;
        static CircuitProof from_json(const json &j);
    };

    /**
     * @brief Request to proof server for proof generation
     * Data sent to Proof Server (http://localhost:6300)
     */
    struct ProofGenerationRequest
    {
        std::string circuit_name;                          // "post", "takeDown", etc.
        std::vector<uint8_t> circuit_data;                 // Compiled circuit (.zkir)
        std::map<std::string, std::string> circuit_inputs; // Circuit parameters
        std::map<std::string, WitnessOutput> witnesses;    // Private witness data

        json to_json() const;
        static ProofGenerationRequest from_json(const json &j);
    };

    /**
     * @brief Response from proof server with generated proof
     */
    struct ProofGenerationResponse
    {
        bool success;

        // If success == true
        ProofData generated_proof;

        // If success == false
        std::string error_message;
        std::string error_code;

        // Metadata from server
        std::map<std::string, std::string> metadata;

        // Performance metrics
        uint64_t generation_time_ms; // How long proof generation took
        uint64_t constraints_evaluated;

        json to_json() const;
        static ProofGenerationResponse from_json(const json &j);
    };

    /**
     * @brief Transaction with embedded ZK proof
     * Ready for submission to Midnight network
     */
    struct ProofEnabledTransaction
    {
        std::string transaction_id;
        std::string transaction_hex; // UTXO transaction data
        CircuitProof circuit_proof;  // ZK proof for contract execution

        // Optional: Ed25519 signature for transaction authorization
        std::string ed25519_signature;
        std::string public_key;

        // Ledger state update after this transaction
        std::map<std::string, std::string> ledger_updates; // field_name => new_value

        json to_json() const;
        static ProofEnabledTransaction from_json(const json &j);
    };

    /**
     * @brief Result of proof generation attempt
     */
    struct ProofResult
    {
        bool success;
        CircuitProof proof;
        std::string error_message;

        // Validation results
        bool proof_verified_locally = false;
        bool public_inputs_valid = false;
        bool witnesses_valid = false;
    };

    /**
     * @brief Ledger state for private state management
     * Tracks on-chain and off-chain state
     */
    struct LedgerState
    {
        std::string contract_address;
        json public_state;  // On-chain state (all fields)
        json private_state; // Off-chain state (witness fields like secretKey)
        uint64_t block_height;
        std::string block_hash;

        json to_json() const;
        static LedgerState from_json(const json &j);
    };

    /**
     * @brief Helper functions for ZK types
     */
    namespace types_util
    {
        /**
         * Convert 32-byte commitment to hex string
         */
        std::string commitment_to_hex(const std::vector<uint8_t> &commitment);

        /**
         * Convert hex string to 32-byte commitment
         */
        std::vector<uint8_t> hex_to_commitment(const std::string &hex);

        /**
         * Validate proof size (must be reasonable)
         */
        bool is_valid_proof_size(size_t size);

        /**
         * Validate public inputs are well-formed
         */
        bool is_valid_public_inputs(const PublicInputs &inputs);

        /**
         * Create empty proof for testing
         */
        CircuitProof create_test_proof(const std::string &circuit_name);
    }

} // namespace midnight::zk
